# Generated by Django 5.2.4 on 2025-08-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_options_alter_blogs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='is_feachered',
            new_name='is_featured',
        ),
    ]
